# Generated by Django 5.2.7 on 2025-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0002_remove_menuitem_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
