# Generated by Django 5.2.7 on 2025-10-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='emoji',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_name',
            field=models.CharField(default='default_cake.png', help_text='Filename of the image (e.g., chocolate_cake.png). Place files in static/bakery/img/.', max_length=50),
        ),
    ]
